# yml is a data serialization language that is readable by humans and computers.

version: "3.12"
services: 
  app:
    build: .
    volumes:
      - .:/django-polls
    ports:
      - 8000:8000
    image: app:django-polls
    container_name: my_first_django_container
    command: python manage.py runserver 0.0.0.0:8000